#!/usr/bin/env bash
# Transfers a file from our clent to a server. It acceps 4
# Parameters - the pathe to the file to be transferred, IP of the
# server to transfer to, the username scp connects with and the SSH
# private key path that the scp uses.

# Function to display usage
usage() {
  echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 1
}

# Check if the arg is less than 4
if [ "$#" -lt 4 ]; then
  usage
fi

# Assign variables to args passed
FILE_PATH=$1
SERVER_IP=$2
USERNAME=$3
SSH_KEY_PATH=$4

# Transfer the file using scp with strict host key checking disabled
scp -i "$SSH_KEY_PATH" -o StrictHostKeyChecking=no "$FILE_PATH" "$USERNAME@$SERVER_IP:~/"

# Check if the scp command was successful
if scp -i "$SSH_KEY_PATH" -o StrictHostKeyChecking=no "$FILE_PATH" "$USERNAME@$SERVER_IP:~/"; then
  echo "File transferred successfully."
else
  echo "File transfer failed."
  exit 1
fi
