#!/usr/bin/env bash
# Install nginx on web-01 server and follow certain requirements

# Update package list and install nginx
sudo apt update
sudo apt install nginx -y

# Ensure firewall does not restrict
sudo ufw allow 'Nginx HTTP'
# Create a simple "Hello World!" content
echo "Hello World!" > /var/www/html/index.html

# Restart Nginx using the service instead of systemctl
service nginx restart
