#!/usr/bin/env bash
# Install nginx on web-01 server and follow certain requirements

# Update package list and install nginx
apt-get update
apt-get install -y nginx

# Create a simple "Hello World!" content
echo "Hello World!" | sudo tee /var/www/html/index.html

# Ensure Nginx is listening on port 80
sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default
sed -i 's/listen \[::\]:80 default_server;/listen \[::\]:80;/g' /etc/nginx/sites-available/default

# Restart Nginx using the service instead of systemctl
service nginx restart

# Exit the script
exit 0
