#!/usr/bin/env bash
# Configures a new ubuntu machine by installing
# Nginx where it should be listening on port 80
# Serve a page that would return a Hello World string
#


echo -e "Updating and installing Nginx.\n"
sudo apt-get update -y -qq && \
         sudo apt-get install nginx -y

# starting nginx service
sudo service nginx start

# allowing nginx on firewall
sudo ufw allow 'Nginx HTTP'

# Backup default index
sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bak

# Setting up /redirect_me to a youtube video
sudo sed -i '/server {/ {N; a \        location /redirect_me { \            return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4; \        }}' /etc/nginx/sites-available/default

# Restarting nginx
sudo service nginx restart
