#!/usr/bin/env bash
# Include page not found - error_404 configuration

# Update package
sudo apt update

# Install Nginx if not available
sudo apt install nginx -y

# Start nginx
sudo service nginx start

# Allow Nginx on firewall
sudo ufw allow 'Nginx HTTP'

# Backup default configuration
sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bak

# Setting up /redirect_me to a youtube video
sudo sed -i '24i\	rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/def

# Write page content
echo "Ceci n'est pas une page" >> /var/www/html/error_404.html
sudo sed -i '25i\	error_page 404 /error_404.html;' /etc/nginx/sites-available/default

# Restart nginx
sudo service nginx restart
