#!/usr/bin/env bash
# Running and listening on port 80 of all the server’s active IPv4 IPs

sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
# Restart Nginx to apply changes
sudo service nginx restart
