#!/usr/bin/env bash
# Displays number and message if superstitious number.

count=1
while [ $count -le 20 ]; do
    case $count in
        4)
	    echo "$count"
	    echo "bad luck from China"
	    ;;
	9)
	    echo "$count"
	    echo "bad luck from Japan"
	    ;;
	17)
	    echo "$count"
	    echo "bad luck from Italy"
	    ;;
	*)
	    echo "$count"
	    ;;
    esac
	((count++))
done
