#!/usr/bin/env bash
# This script configures an Ubuntu server

# Backup the original /etc/hosts file
sudo cp /etc/hosts /etc/hosts.bak

# Clear the file
sudo truncate -s 0 /etc/hosts

# Add the required entries
sudo tee /etc/hosts > /dev/null <<EOL
127.0.0.1   localhost
127.0.0.2   localhost
8.8.8.8     facebook.com
EOL
